apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 1
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: sidekick
          image: ghcr.io/project-n-oss/sidekick:latest
          command: ["sidekick", "serve"]
          env:
            - name: SIDEKICK_APP_CLOUDPLATFORM
              value: AWS
          ports:
            - containerPort: 7075
        - name: app
          image: alpine
          command: ["/bin/sh", "-c", "echo Hello from BusyBox; sleep 36000"]
          env:
            - name: S3_ENDPOINT
              value: http://localhost:7075
